services:
  postgres:
    image: postgres:15
    container_name: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  fastapi:
    image: fahad343/fastapi:latest
    # container_name: fastapi
    # command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "80:8000"
    depends_on:
      - postgres
    env_file:
      - .env

volumes:
  postgres_data:
