name: Build and Deploy Code

on: [push, pull_request]



jobs:
  job1:
     env:
      DATABASE_HOSTNAME=postgres 
      DATABASE_PORT=5432
      DATABASE_PASSWORD=toor
      DATABASE_NAME=fastapi
      DATABASE_USERNAME=postgres
      SECRET_KEY=N3b9rXqL6wF8uJ0pK4tS7vY2mH1cZ5xQnA8eR3fV0gB6yW9d
      ALGORITHM=HS256
      ACCESS_TOKEN_EXPIRE_MINUTES=60

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'  # use 3.12 or 3.11, since 3.13 is super new and may not have wheels yet

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install -r requirement.txt

      - name: test with pytest
        run: |
          pip install pytest
          pytest
